name: create-model

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: 
  
jobs:
  build-model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - run: pip install -r requirements.txt
    # cleans output for later upload only new created tflites.
    - run: rm output/*
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "dig-class100-s2.ipynb"
        #params: "PATHTOPARAMS.json"
        isReport: False
        poll: False
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: notebook-results
        path: |
          ${{ RUNNER.temp }}/nb-runner 
          output/*
      env:
        RUNNER: ${{ toJson(runner) }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tflite-model
        path: output/*.tflite
     
